compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp



supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs
