compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@feathersjs/express@*":
    peerDependenciesMeta:
      "@feathersjs/feathers":
        optional: true
      "@types/express-serve-static-core":
        optional: true
  "@storybook/addon-docs@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      webpack:
        optional: true
  "@storybook/docs-tools@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/mdx1-csf@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@storybook/telemetry@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  acorn-walk@*:
    peerDependenciesMeta:
      acorn:
        optional: true
  cloudinary-react@*:
    peerDependenciesMeta:
      lodash:
        optional: true
  express-jwt@*:
    peerDependenciesMeta:
      express:
        optional: true
  express-static-gzip@*:
    peerDependenciesMeta:
      "@types/serve-static":
        optional: true
  express-unless@*:
    peerDependenciesMeta:
      express:
        optional: true
  feathers-sequelize@*:
    peerDependenciesMeta:
      "@feathersjs/feathers":
        optional: true
  react-popover@*:
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  redux-mock-store@1.5.4:
    peerDependenciesMeta:
      redux:
        optional: true
  semantic-ui-css@*:
    peerDependenciesMeta:
      react:
        optional: true
  swagger-parser@*:
    peerDependenciesMeta:
      openapi-types:
        optional: true
  unleash-server@*:
    peerDependenciesMeta:
      react:
        optional: true

pnpIgnorePatterns:
  - ./e2e/**
  - ./github-apps/cloud-build-on-prs/cloud-functions/cloudbuild-update/**
  - ./github-apps/cloud-build-on-prs/cloud-functions/github-pr-update/**
  - ./ci/buildr
  - ./ci/stackhawk

pnpMode: strict

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs
