name: Check Changes

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      [
        '**.json5',
      ]
    types: [opened, reopened, synchronize]

jobs:
  configcheck:
    name: Checking files
    runs-on: ubuntu-latest

    steps:
      - name: Install yarn
        run: yarn install

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.17.1

      - name: Setup Typescript environment
        run: npm install ts-node 
        
      - name: CheckoutRepo
        uses: actions/checkout@v2 
      
      - name: Generate and check computed configs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}``
        run: $GITHUB_WORKSPACE/generate.sh


