name: Check Changes

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

jobs:
  configcheck:
    name: Checking files
    runs-on: ubuntu-latest

    steps:
      - name: Install yarn
        run: yarn install

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.17.1

      - name: CheckoutRepo
        uses: actions/checkout@v2 

      - name: pwd
        run: pwd
      
      - name: ls
        run: ls
      
      - name: Run generate files
        # run: $GITHUB_WORKSPACE/backend/core/bin/generate-computed-configs.sh
        
        run: yarn generate-file
        

      # This step will evaluate the repo status and report the change
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      # You can now access a variable indicating if there have been changes
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: echo "Changes exist"
