name: Check compited config

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

jobs:
  configcheck:
    name: Checking computed config files
    runs-on: ubuntu-latest

    steps:
      - name: Install yarn
        run: yarn install

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.17.1

      - name: CheckoutRepo
        uses: actions/checkout@v2 

      - name: Run generate computed files
        # run: $GITHUB_WORKSPACE/backend/core/bin/generate-computed-configs.sh
        run: yarn generate
        working-directory: '/'
